### ISSUE TITLE
http codes

### ISSUE THREAD

**Issue by tehstun** [CodeDoesGood/Mercury-Web#10]
Set the correct HTTP codes within all the middle-wares

**Comment by DirkDeVisser** [comment]
Didn't have time to work on this. If someone else wants to do this, go ahead. Else i will try to look at this next friday.

**Comment by tehstun** [comment]
@DirkDeVisser  Thank you for the update, I will have a look into this.

**Comment by tehstun** [comment]
Pull request currently open for checking here #16
