### ISSUE TITLE
database schema

### ISSUE THREAD

**Issue by tehstun** [CodeDoesGood/Mercury-Web#11]
Research and find a software that will allow you to create tables that can be exported as a sql scheme for quickly creating a database structure.

**Comment by tehstun** [comment]
Hows this going @Doug-Luce, are we good to go with the current one or are we going to try the web version that @swiftcode said he was using recently? 

Thanks for the work!

**Comment by Doug-Luce** [comment]
So far DBDesigner Fork has worked well, but doesn't support making an enum type, but we can still model it as @swiftcode suggested. He is going to show me an example so we can accurately model the data. Once that is done it's mostly data entry into DBDesigner Fork and choosing the correct types. Here is the link to the software https://sourceforge.net/projects/dbdesigner-fork/

**Comment by tehstun** [comment]
Any update? Does this cover us for the migration over to it?

**Comment by tehstun** [comment]
@Doug-Luce Can I get a upset about this?

**Comment by tehstun** [comment]
I have decided to go with: http://dbdesigner.net over the local application, so that anyone on any platform is able to see, use and update the schema.

http://dbdesigner.net
