### ISSUE TITLE
Define admin dashboard

### ISSUE THREAD

**Issue by Leikela** [CodeDoesGood/Mercury-Web#20]
In the software specs, an admin dashboard is listed as one of the pages but there is no design for it yet.  The features of this need to be defined before design can begin.

**Comment by Leikela** [comment]
Based on existing specs, an Admin should be able to do the following from their dashboard: 
- Create a company announcement
- Create a new project
- User profile directory (core business group plus all volunteers = users), view to include admin only functions: view user email/phone, add comment on user, export "public" comments to PDF for submitting to companies as references
- Manage permissions for all users (i.e. add/remove users from user groups)
- Monitor which users have not confirmed that they have read company announcements (need to consider best approach... by user: total unread? unread in the past x days?  # or %, by announcement: number unread or names?)

**Comment by Leikela** [comment]
How about contact info for clients?

**Comment by northtwilight** [comment]
Good suggestion!

**Comment by tehstun** [comment]
I have had no involvement in this design and wouldn't know where to point you to get this kind of information about design.

@northtwilight  who was heading up design for the mercury project ?

**Comment by northtwilight** [comment]
Just getting some more details on this, will update after work (5pm PST)

**Comment by tehstun** [comment]
Any update on the question referencing to the update with the above message.

**Comment by northtwilight** [comment]
Sorry for the super-late reply - basically as I understood it, it was handled by Claudio Tellez, but to what extent I have no idea, as he's never replied to my queries on the subject. Going forward let's just stick to @Leikela 's points in [#44 Create Wireframes](https://github.com/CodeDoesGood/Mercury-Web/issues/44) . Apologies for this.
