### ISSUE TITLE
Changes & Suggestions to Databases Schema

### ISSUE THREAD

**Issue by swiftcode** [CodeDoesGood/Mercury-Web#21]
Here are some topics for discussion for the database schema.   Some of these I've discussed with @tehstun already.  None of these are set in stone, but these are things we need to think about as we go forward:

1) admin_access_levels:  This should probably not be an enum, UNLESS, we add an access level that corresponds to the permutations of access allowed.  For instance, level 0 might be ALL access with 1 being read, 2 being read/write, etc.  

2) Separate date and time fields should be converted to a single datetime datatype.  

3) comment:  In the comment table, we can lose the *title* and rename body to *comment* or something similar.  

4) volunteer_assignment: rename *github_issue_url* to just *issue_url* in the spirit of keeping it as generic as possible.

5) volunteer_assignment: add fields - completed_datetime, created_datetime and  modified_datetime

6) volunteer_status_types: add a *code* field or something similar so that it can be displayed on reports.

7) enum_project_status: Additional values we want - On Hold, Canceled, Pending Approval, Approval Denied

8) We want to get rid of the label *Hatchling*.   Rename to volunteer or developer.  We may get rid of the idea of hatching altogether and just have admins, mentors and developers.

**Comment by swiftcode** [comment]
enum_project_status: Add _created_datetime_ and _modified_datetime field_

**Comment by swiftcode** [comment]
@brandonpas @DirkDeVisser We are officially getting rid of the term hatchling.  So, we can replace it with either volunteer or developer.  I'm more inclined to go with developer.   We can start the discussion if we'd need levels of developers (1 - 8), but I don't think that the current volunteer base warrants having different levels.  We can reduce the fields in the tables that mention hatchlings (developer_types, position, etc).

**Comment by swiftcode** [comment]
Additional suggestions in no particular order. Open for discussion.

Traditionally, with few exceptions, table names are singular (so that queries would be access_level.level instead of access_levels.level).  

Is *data_entry_date* the date the data was entered in the spreadsheet?  If so, then it can be a date instead of a datetime.  

We can add an int to admin_access_level to correspond to the actual level.  So, admin_access.level.level would be the user's access level.  This would let us query (for instance), access levels greater than *n* (for limited access).   Level 0 would be ALL privileges, with larger numbers being a decrease in access privileges.

Fields that are FK in tables should have an *_id* suffix, so that it is readily apparent that it references another table.  

Table *project_sub_activity*: The *team* fields can be refactored to point to a team table (with a many relationship) and the existing fields can be the FK.  

Do we want to still track the is_hatchling and developer_level in the volunteer table?  If we do, that's fine, but since we won't be using that going forward, all the current data will be historical at best.

Will tables *developer_type* and *roll_type* need an additional field other than description?

**Comment by tehstun** [comment]
This has all been done now right? @swiftcode

**Comment by tehstun** [comment]
Content changed and meets this current standard.
