### ISSUE TITLE
Add rate-limiting for all ips connecting.

### ISSUE THREAD

**Issue by tehstun** [CodeDoesGood/Mercury-Web#48]
10 requests per second?

**Comment by swiftcode** [comment]
Are you asking what it should be set at?  I'd make it configurable.  Set some value MAX_REQUESTS, for example.  It's difficult to say what the initial value should be since we don't have any metrics.  10 sounds reasonable to begin with.  Can always make adjustments later.

**Comment by tehstun** [comment]
More of a reminder but yes!
